eshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] +  (static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

shop/urls.py
from django.urls import path
from shop import views
from shop.views import AddToCartView, UpdateCartView, CheckoutView

urlpatterns = [
    path('', views.index, name='index'),
    path('shop/', views.shop, name='shop'),
    path('product/<int:pk>/', views.ProductDetailView.as_view(), name='product'),
    path('register/', views.register, name='register'),
    path('mywishlist/', views.WishlistByUserListView.as_view(), name='my-wishlist'),
    path('customer_profile/', views.customer_profile, name='customer_profile'),
    path('wishlist/toggle/<int:product_id>/', views.toggle_wishlist, name='toggle_wishlist'),
    path('update_cart/', UpdateCartView.as_view(), name='update_cart'),
    path('add_to_cart/', AddToCartView.as_view(), name='add_to_cart'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
]

shop/models.py
from PIL import Image
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Avg, Count
from django.utils import timezone


class Category(models.Model):
    category_name = models.CharField(max_length=50)
    logo = models.CharField(max_length=50,
                            default='fluent:search-12-regular',
                            help_text='Get logo (Icon name:) from https://icon-sets.iconify.design/ph/ ,'
                                      'example: ph:headphones')

    def __str__(self):
        return self.category_name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

class Product(models.Model):
    product_name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=1000)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="products")
    description = models.TextField(max_length=1000, blank=True, null=True)
    image = models.ImageField(upload_to='products', blank=True, null=True)

    def __str__(self):
        return self.product_name

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.image:
            img = Image.open(self.image.path).convert("RGBA")
            img_width, img_height = img.size
            max_size = max(img_width, img_height)
            img_alfa = Image.new("RGBA", (max_size, max_size), (0, 0, 0, 0))
            x = (max_size - img_width) // 2
            y = (max_size - img_height) // 2
            img_location = (x, y)
            img_alfa.paste(img, img_location)
            img_alfa.save(self.image.path, format="PNG")

    def average_rating(self):
        avg = self.productreview_set.aggregate(Avg('rating'))['rating__avg']
        return avg or 0

    def count_rating(self):
        count = self.productreview_set.aggregate(Count('rating'))['rating__count']
        return count




class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    phone = models.CharField(max_length=50, blank=True, null=True)
    address = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = 'Customer'
        verbose_name_plural = 'Customers'


class Wishlist(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='wishlist')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.customer.user.username} * {self.product}'

    class Meta:
        unique_together = ('customer', 'product')
        verbose_name = 'Wishlist'
        verbose_name_plural = 'Wishlists'

class ProductReview(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, blank=True)
    rating = models.IntegerField(choices=[(i, i) for i in range(1, 6)])
    content = models.TextField(max_length=1000, default='', blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return f'{self.date_created} * {self.customer.user.username} * {self.rating}'

    class Meta:
        unique_together = ('customer', 'product')
        ordering = ['-date_created']
        verbose_name = 'Product review'
        verbose_name_plural = 'Product reviews'

class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    date = models.DateField(default=timezone.now)

    ORDER_STATUS = (
        ('cart', 'Shopping Cart'),
        ('payment', 'Awaiting Payment'),
        ('shipping', 'Awaiting Shipment'),
        ('shipped', 'Shipped'),
        ('delivered', 'Delivered'),
    )

    status = models.CharField(
        choices=ORDER_STATUS,
        blank=True,
        default='cart',
        help_text='Status',
    )

    def __str__(self):
        return f'{str(self.date)} * {self.status} * {self.customer}'

    class Meta:
        verbose_name = 'Order'
        verbose_name_plural = 'Orders'

class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f'{str(self.order.date)} * {self.product} * {self.quantity} * {self.order.customer}'

    class Meta:
        verbose_name = 'Order product'
        verbose_name_plural = 'Order products'

shop/forms.py
from django.contrib.auth.models import User

from .models import ProductReview, Customer
from django import forms

class ProductReviewForm(forms.ModelForm):
    rating = forms.ChoiceField(
        choices=[(i, f"{i} \u2B50") for i in range(1, 6)],
        widget=forms.RadioSelect,
        error_messages={'required': 'Please select one of the options.'}
    )
    class Meta:
        model = ProductReview
        fields = ('content', 'product', 'customer', 'rating')
        widgets = {
            'product': forms.HiddenInput(),
            'customer': forms.HiddenInput()
        }

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

class CustomerUpdateForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['phone', 'address']

shop/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views import generic, View
from django.views.decorators.csrf import csrf_protect
from django.views.generic import DetailView, TemplateView
from django.views.generic.edit import FormMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from shop.forms import ProductReviewForm, UserUpdateForm, CustomerUpdateForm
from shop.models import Category, Product, Wishlist, Customer, ProductReview, Order, OrderProduct
from django.db.models import Q


def index(request):
    categories = Category.objects.all()
    return render(request, 'index.html', {'categories': categories})


def shop(request):
    categories = Category.objects.all()
    query = request.GET.get('query')
    category_id = request.GET.get('category')
    products = Product.objects.all()
    if query:
        products = products.filter(Q(product_name__icontains=query))
    if category_id:
        products = products.filter(category__id=category_id)
    if request.user.is_authenticated:
        wishlist_products = request.user.customer.wishlist.values_list('product', flat=True)
    else:
        wishlist_products = []

    context = {
        'categories': categories,
        'products': products,
        'query': query if query else '',
        'wishlist_products': wishlist_products,

    }
    return render(request, 'shop.html', context=context)


class ProductDetailView(FormMixin, DetailView):
    model = Product
    template_name = 'product.html'
    form_class = ProductReviewForm

    def get_success_url(self):
        return reverse('product', kwargs={'pk': self.object.id})

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        if form.cleaned_data['rating'] is None:
            form.add_error('rating', 'Rating is required!')
            return self.form_invalid(form)

        customer = Customer.objects.get(user=self.request.user)
        product = self.object

        is_existing_review = ProductReview.objects.filter(customer=customer, product=product).first()
        if is_existing_review:
            is_existing_review.rating = form.cleaned_data['rating']
            is_existing_review.content = form.cleaned_data['content']
            is_existing_review.save()
        else:
            form.instance.product = product
            form.instance.customer = customer
            form.save()

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if self.request.user.is_authenticated:
            wishlist_products = self.request.user.customer.wishlist.values_list('product', flat=True)
            wishlist_count = self.request.user.customer.wishlist.count()
        else:
            wishlist_products = []
            wishlist_count = 0

        context['wishlist_products'] = wishlist_products
        context['wishlist_count'] = wishlist_count
        context['stars'] = [5,4,3,2,1]

        return context


@csrf_protect
def register(request):
    if request.method == "POST":
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
        if password == password2:
            if User.objects.filter(username=username).exists():
                messages.error(request, f'Username {username} is already taken!')
                return redirect('register')
            else:
                if User.objects.filter(email=email).exists():
                    messages.error(request, f'A user with email {email} is already registered!')
                    return redirect('register')
                else:
                    User.objects.create_user(username=username, email=email, password=password)
                    messages.info(request, f'User {username} has been registered!')
                    return redirect('login')
        else:
            messages.error(request, 'Passwords do not match!')
            return redirect('register')
    return render(request, 'register.html')


@login_required
def customer_profile(request):
    if request.method == "POST":
        user_form = UserUpdateForm(request.POST, instance=request.user)
        customer_form = CustomerUpdateForm(request.POST, instance=request.user.customer)
        if user_form.is_valid() and customer_form.is_valid():
            user_form.save()
            customer_form.save()
            messages.success(request, f"Profile updated")
            return redirect('customer_profile')
    else:
        user_form = UserUpdateForm(instance=request.user)
        customer_form = CustomerUpdateForm(instance=request.user.customer)

    context = {
        'user_form': user_form,
        'customer_form': customer_form,
    }
    return render(request, 'customer_profile.html', context)


class WishlistByUserListView(LoginRequiredMixin, generic.ListView):
    model = Wishlist
    template_name = 'my_wishlist.html'
    paginate_by = 10

    def get_queryset(self):
        return Wishlist.objects.filter(customer__user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if self.request.user.is_authenticated:
            wishlist_products = self.request.user.customer.wishlist.values_list('product', flat=True)
            wishlist_categories = Category.objects.filter(
                products__wishlist__customer__user=self.request.user).distinct()
        else:
            wishlist_products = []
            wishlist_categories = []

        context['wishlist_products'] = wishlist_products
        context['wishlist_categories'] = wishlist_categories

        return context


@login_required
def toggle_wishlist(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    customer = request.user.customer

    wishlist_item, created = Wishlist.objects.get_or_create(customer=customer, product=product)
    if not created:
        wishlist_item.delete()
        messages.info(request, 'Product removed from wishlist.')
    else:
        messages.success(request, 'Product added to wishlist.')
    return redirect(request.META.get('HTTP_REFERER', 'shop'))


class AddToCartView(View):
    def post(self, request):
        product_id = request.POST.get('product_id')
        quantity = int(request.POST.get('quantity', 1))

        product = Product.objects.filter(id=product_id).first()
        if not product:
            return redirect('index')

        if request.user.is_authenticated:
            customer = Customer.objects.get(user=request.user)
            order, created = Order.objects.get_or_create(customer=customer, status='cart')
            order_product, created = OrderProduct.objects.get_or_create(order=order, product=product)
            if created:
                order_product.quantity = quantity
            else:
                order_product.quantity += quantity
            order_product.save()
        else:
            cart = request.session.get('cart', {})
            cart[str(product_id)] = cart.get(str(product_id), 0) + quantity
            request.session['cart'] = cart

        return redirect(request.META.get('HTTP_REFERER', 'shop'))


class UpdateCartView(View):
    def post(self, request):
        product_id = request.POST.get('product_id')
        action = request.POST.get('action')
        cart_open = request.POST.get('cart_open')

        if request.user.is_authenticated:
            customer = Customer.objects.get(user=request.user)
            order = Order.objects.get(customer=customer, status='cart')
            product = OrderProduct.objects.filter(order=order, product_id=product_id).first()

            if product:
                if action == 'plus':
                    product.quantity += 1
                    product.save()
                elif action == 'minus':
                    product.quantity -= 1
                    product.save()
                    if product.quantity <= 0:
                        product.delete()
        else:
            cart = request.session.get('cart', {})
            if product_id in cart:
                if action == 'plus':
                    cart[product_id] += 1
                elif action == 'minus':
                    cart[product_id] -= 1
                    if cart[product_id] <= 0:
                        del cart[product_id]
            request.session['cart'] = cart

        redirect_url = '/'
        if cart_open:
            redirect_url += '?cart_open=1'

        return redirect(redirect_url)


class CheckoutView(TemplateView):
    template_name = 'checkout.html'

    def post(self, request):
        cart = request.session.get('cart', {})
        if not cart:
            return redirect('index')

        if request.user.is_authenticated:
            customer = Customer.objects.get(user=request.user)
        else:
            customer = Customer.objects.create(user=None)

        order = Order.objects.create(customer=customer, status='payment')
        products = Product.objects.filter(id__in=cart.keys())

        for product in products:
            quantity = cart.get(str(product.id), 1)
            OrderProduct.objects.create(order=order, product=product, quantity=quantity)

        request.session['cart'] = {}
        return redirect('order_success', order_id=order.id)

shop/templates/checkout.html
{% extends "base.html" %}

{% block content %}
<div class="container py-5">
  <h2 class="mb-4 text-center">Checkout</h2>

  {% if cart_products %}
    <table class="table table-bordered">
      <thead class="table-light">
        <tr>
          <th>Product</th>
          <th class="text-center">Quantity</th>
          <th class="text-end">Subtotal</th>
        </tr>
      </thead>
      <tbody>
        {% for item in cart_products %}
          <tr>
            <td>{{ item.product.product_name }}</td>
            <td class="text-center">{{ item.quantity }}</td>
            <td class="text-end">{{ item.subtotal }} €</td>
          </tr>
        {% endfor %}
        <tr class="fw-bold">
          <td colspan="2" class="text-end">Total:</td>
          <td class="text-end">{{ cart_total }} €</td>
        </tr>
      </tbody>
    </table>

    <form method="post">
      {% csrf_token %}
      <div class="text-center">
        <button type="submit" class="w-25 btn btn-primary btn-lg">Place Order</button>
      </div>
    </form>

  {% else %}
    <p class="text-center">Your cart is empty.</p>
  {% endif %}
</div>
{% endblock %}

shop/templates/customer_profile.html
{% extends "base.html" %}

{% block content %}
{% load static %}
{% load widget_tweaks %}
  <section id="customer_profile_form" style="background: url('{% static 'images/background-img.png' %}') no-repeat;">
    <div class="container ">
        <div class="row my-2 py-0">
            <div class="offset-md-3 col-md-6 my-5 ">
                <h2 class="display-3 fw-normal text-center">My profile</span>
                </h2>
              <form method="post" >
                {% csrf_token %}
                <div class="mb-3">
                  {{ user_form.username|add_class:"form-control form-control-lg"|attr:"placeholder:Enter Your Username" }}
                </div>
                <div class="mb-3">
                    {{ user_form.first_name|add_class:"form-control form-control-lg"|attr:"placeholder:Enter Your First Name" }}
                </div>
                <div class="mb-3">
                    {{ user_form.last_name|add_class:"form-control form-control-lg"|attr:"placeholder:Enter Your Last Name" }}
                </div>
                <div class="mb-3">
                    {{ user_form.email|add_class:"form-control form-control-lg"|attr:"placeholder:Enter Your Email" }}
                </div>
                <div class="mb-3">
                    {{ customer_form.phone|add_class:"form-control form-control-lg"|attr:"placeholder:Enter Your Phone Number" }}
                </div>
                <div class="mb-3">
                    {{ customer_form.address|add_class:"form-control form-control-lg"|attr:"placeholder:Enter Your Address" }}
                </div>
                <div class="d-grid gap-2">
                <button type="submit" class="btn btn-dark btn-lg rounded-1">Update</button>
                <input type="hidden" name="next" value="{{ next }}" />
                </div>
              </form>
              <p><a href="{% url 'password_reset' %}">Forgot your password?</a></p>
              </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

shop/templates/index.html
{% extends "base.html" %}

{% block content %}
{% load static %}
{% if random_products %}
  <section id="banner" style="background: #F9F3EC;">
    <div class="container">
      <div class="swiper main-swiper">
        <div class="swiper-wrapper">
          {% for product in random_products %}
          <div class="swiper-slide py-5">
            <div class="row banner-content align-items-center">
              <div class="img-wrapper col-md-5">
                <img src="{{ product.image.url }}" alt="{{ product.product_name }}" class="img-fluid">
              </div>
              <div class="content-wrapper col-md-7 p-5 mb-5">
                <h2 class="banner-title display-1 fw-normal">Best offers for <span class="text-primary">You</span>!!!</h2>
                <a href="{% url 'product' product.id %}" class="btn btn-outline-dark btn-lg text-uppercase fs-6 rounded-1">
                  Check It
                  <svg width="24" height="24" viewBox="0 0 24 24" class="mb-1">
                    <use xlink:href="#arrow-right"></use>
                  </svg>
                </a>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
        <div class="swiper-pagination mb-5"></div>
      </div>
    </div>
  </section>
{% endif %}

  <section id="categories">
    <div class="container my-3 py-5">
      <div class="row my-5">

        {% for category in categories %}
        <div class="col text-center">
          <a href="{% url 'shop' %}?category={{ category.id }}" class="categories-item">
            <iconify-icon class="category-icon" icon="{{ category.logo }}"></iconify-icon>
            <h5>{{ category.category_name }}</h5>
          </a>
        </div>
        {% endfor %}

      </div>
    </div>
  </section>

  {% for category in categories %}
    <section id="{{ category.category_name }}" class="my-5 overflow-hidden">
      <div class="container pb-5">

        <div class="section-header d-md-flex justify-content-between align-items-center mb-3">
          <h2 class="display-3 fw-normal">{{ category.category_name }}</h2>
          <div>
            <a href="{% url 'shop' %}?category={{ category.id }}" class="btn btn-outline-dark btn-lg text-uppercase fs-6 rounded-1 item {{ product.category.id }}" data-filter=".{{ category.id }}">
              shop now
              <svg width="24" height="24" viewBox="0 0 24 24" class="mb-1">
                <use xlink:href="#arrow-right"></use>
              </svg></a>
          </div>
        </div>

          <div class="products-carousel swiper">
            <div class="swiper-wrapper">
              {% for product in category.products.all %}
              <div class="swiper-slide">
                {% include 'single_product_card.html' %}
              </div>
              {% endfor %}
            </div>
          </div>

      </div>
    </section>
  {% endfor %}
{% endblock %}

shop/templates/my_wishlist.html
{% extends "base.html" %}

{% block content %}
{% load static %}

  <section id="foodies" class="my-5">
    <div class="container my-5 py-5">
        <h2>My wishlist:</h2>
      <div class="section-header d-md-flex justify-content-between align-items-center">
        <div class="mb-4 mb-md-0">
          <p class="m-0">
            <button class="filter-button me-4  active" data-filter="*">ALL</button>
            {% for category in wishlist_categories %}
                <button class="filter-button me-4 " data-filter=".{{ category.id }}">{{ category.category_name }}</button>
            {% endfor %}
          </p>
        </div>
      </div>
      <div class="isotope-container row">
        {% if wishlist_list %}
        {% for item in wishlist_list %}
          {% with product=item.product %}
            <div class="item {{ product.category.id }} col-md-4 col-lg-3 my-4">
              {% include 'single_product_card.html' %}
            </div>
          {% endwith %}
        {% endfor %}
      {% else %}
        <p>Your wishlist is empty. Start adding your favorite items!</p>
      {% endif %}
      </div>
    </div>
  </section>
{% endblock %}

shop/templates/product.html
{% extends "base.html" %}

{% block content %}
{% load static %}
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6">
      <img src="{{ product.image.url }}" class="img-fluid rounded-4 " alt="product image">
    </div>
    <div class="col-md-6 d-flex flex-column">
      <h2>{{ product.product_name }}</h2>
        <span class="rating secondary-font">
          {% with product.average_rating as avg_rating %}
            {% for i in "12345" %}
              {% if avg_rating >= forloop.counter %}
                <iconify-icon icon="mdi:star" class="text-primary"></iconify-icon>
              {% elif avg_rating > forloop.counter0 and avg_rating < forloop.counter %}
                <iconify-icon icon="mdi:star-half-full" class="text-primary"></iconify-icon>
              {% else %}
                <iconify-icon icon="mdi:star-outline" class="text-muted"></iconify-icon>
              {% endif %}
            {% endfor %}
            {{ avg_rating }} ({{ product.count_rating }}  Reviews)
          {% endwith %}
        </span>
      <h4 class="text-primary">{{ product.price }} €</h4>
      <p class="mt-3 text-muted">{{ product.description }}</p>
      <div class="d-flex flex-wrap mt-3">
        <form method="post" action="{% url 'add_to_cart' %}" style="display: inline;">
          {% csrf_token %}
          <input type="hidden" name="product_id" value="{{ product.id }}">
          <input type="hidden" name="quantity" value="1">
          <button type="submit" type="button" class="btn btn-outline-dark me-3 px-4 pt-3 pb-3 text-uppercase fs-6 rounded-1">
            Add to Cart
          </button>
        </form>
        {% if user.is_authenticated %}
        <a href="{% url 'toggle_wishlist' product.id %}" class="btn btn-outline-dark me-3 px-4 pt-3 pb-3 text-uppercase fs-6 rounded-1">
          <iconify-icon icon="fluent:heart-28-filled"
                        class=" {% if product.id in wishlist_products %}text-primary{% else %}text-muted{% endif %}">
          </iconify-icon>
          <span class="tooltip-text">
            {% if product.id in wishlist_products %}
            {{ 'Remove from wishlist' }}
            {% else %}
            {{ 'Add to wishlist' }}
            {% endif %}
          </span>
        </a>
        {% endif %}
      </div>
    </div>
  </div>
  </br>
  <h4>Reviews:</h4>
  {% if product.productreview_set.all %}
    {% for review in product.productreview_set.all %}
    <hr>
    {% for i in "12345" %}
      {% if review.rating >= forloop.counter %}
        <iconify-icon icon="mdi:star" class="text-primary"></iconify-icon>
      {% else %}
        <iconify-icon icon="mdi:star-outline" class="text-muted"></iconify-icon>
      {% endif %}
    {% endfor %} </br>
      <strong>{{ review.customer.user.username }}</strong>, <em>{{ review.date_created}}</em>
      <p>{{ review.content }}</p>
    {% endfor %}
  {% else %}
    <p>This product has no reviews.</p>
  {% endif %}
  {% if user.is_authenticated %}
  <div class="fieldWrapper">
    <hr><br/>
    <h4>Leave a review:</h4>
    <form action="" method="post">
      {% csrf_token %}
      {% if form.errors %}
      <ul class="errorlist">
      {% for field in form %}
        {% for error in field.errors %}
          <li>{{ field.label }}: {{ error }}</li>
        {% endfor %}
      {% endfor %}
      {% for error in form.non_field_errors %}
        <li>{{ error }}</li>
      {% endfor %}
      </ul>
      {% endif %}
     <label for="id_rating">Rate it:</label></br>
      {{ form.rating }}
      {{ form.content }}</br>
      <input type="submit" value="Save" class="btn btn-outline-dark me-3 px-4 pt-3 pb-3 text-uppercase fs-6 rounded-1">
    </form>
    <hr>
  </div>
  {% endif %}
</div>
{% endblock %}

shop/templates/register.html
{% extends "base.html" %}

{% block content %}
{% load static %}
<section id="register" style="background: url('{% static 'images/background-img.png' %}') no-repeat;">
    <div class="container ">
        <div class="row my-2 py-0">
            <div class="offset-md-3 col-md-6 my-5 ">
                <h2 class="display-3 fw-normal text-center">registration form</h2>
                <form method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <input name="username" type="text" class="form-control form-control-lg" id="username"
                               placeholder="Enter Your Username">
                    </div>
                    <div class="mb-3">
                        <input name="email" type="email" class="form-control form-control-lg" id="email"
                               placeholder="Enter Your Email Address">
                    </div>
                    <div class="mb-3">
                        <input name="password" type="password" class="form-control form-control-lg" id="password"
                               placeholder="Create Password">
                    </div>
                    <div class="mb-3">
                        <input name="password2" type="password" class="form-control form-control-lg" id="password2"
                               placeholder="Repeat Password">
                    </div>
                    <div class="d-grid gap-2">
                        <button type="submit" class="btn btn-dark btn-lg rounded-1">Register it now</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

shop/templates/shop.html
{% extends "base.html" %}

{% block content %}
{% load static %}

  <section id="foodies" class="my-5">
    <div class="container my-5 py-5">
      {% if query %}
        <h2>Search results for '{{query}}':</h2>
      {% endif %}
      <div class="section-header d-md-flex justify-content-between align-items-center">
        <div class="mb-4 mb-md-0">
          <p class="m-0">
            <button class="filter-button me-4  active" data-filter="*">ALL</button>
            {% for category in categories %}
              <button class="filter-button me-4 " data-filter=".{{ category.id }}">{{ category.category_name }}</button>
            {% endfor %}
          </p>
        </div>
      </div>
      <div class="isotope-container row">
        {% for product in products %}
        <div class="item {{ product.category.id }} col-md-4 col-lg-3 my-4">
          {% include 'single_product_card.html' %}
        </div>
        {% endfor %}
      </div>
    </div>
  </section>
{% endblock %}